// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgb-pk4JA_IrMmBUFgH5YdGbJD7pVbmaQ',
    appId: '1:724281899690:web:d28b62cf4b3578d543eed3',
    messagingSenderId: '724281899690',
    projectId: 'dokaz-2d5f5',
    authDomain: 'dokaz-2d5f5.firebaseapp.com',
    storageBucket: 'dokaz-2d5f5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkOingfGlAyQb1O_lGJZOPZAnFMSmYZPY',
    appId: '1:724281899690:android:aa31ad5bff81d86643eed3',
    messagingSenderId: '724281899690',
    projectId: 'dokaz-2d5f5',
    storageBucket: 'dokaz-2d5f5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvz73O8ARWynr_dV8r0fRloI5jhcwfHVc',
    appId: '1:724281899690:ios:1152d28ab6eb5df743eed3',
    messagingSenderId: '724281899690',
    projectId: 'dokaz-2d5f5',
    storageBucket: 'dokaz-2d5f5.firebasestorage.app',
    iosBundleId: 'com.example.dokaz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvz73O8ARWynr_dV8r0fRloI5jhcwfHVc',
    appId: '1:724281899690:ios:1152d28ab6eb5df743eed3',
    messagingSenderId: '724281899690',
    projectId: 'dokaz-2d5f5',
    storageBucket: 'dokaz-2d5f5.firebasestorage.app',
    iosBundleId: 'com.example.dokaz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgb-pk4JA_IrMmBUFgH5YdGbJD7pVbmaQ',
    appId: '1:724281899690:web:ff9ce0d557e0e0ed43eed3',
    messagingSenderId: '724281899690',
    projectId: 'dokaz-2d5f5',
    authDomain: 'dokaz-2d5f5.firebaseapp.com',
    storageBucket: 'dokaz-2d5f5.firebasestorage.app',
  );
}
